# Server settings (ServerProperties)
logging:
 config: config/logback.xml
 level.*: debug
sample:
  samplePackage: org.alan.chess.logic.sample
  samplePath: resources/sample
  roleSaveInterval: 60

zookeeper:
 connects: localhost:2181
 baseSleepTimeMs: 1000
 maxRetries: 3
 marsRoot: alan
cluster:
 type: DATA
 name: DS1
 number: 1
 useGate: false
 tcpAddress:
  port: 11001
  host: 192.168.0.121
 rpcAddress:
  port: 11003
  host: 192.168.0.121

tcp:
 port: ${cluster.tcpAddress.port}
 host: ${cluster.tcpAddress.host}

spring:
 data.mongodb.uri: mongodb://localhost:27017/cardchess
 redis:
  host: localhost
  port: 6379
  password: alan
  database: 2
  
    